version: '3.1'
services:
  db:
    image: mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: s83n38DGB8d72
    networks:
      - skynet
    ports:
      - 33308:3306
    volumes:
        - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  adminer:
    image: adminer
    restart: "no"
    networks:
      - skynet
    ports:
      - 8181:8080
    
networks:
  skynet:
