version: "3"
services: 
  gestion:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}
    volumes:
        - ../sql:/db.sql
  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - ${APP_PORT}:${ADMINER_CONTAINER_PORT}
    